### PR TITLE
properly handle common realloc() mistakes

### PR DESCRIPTION
**Pull request by bryongloden**
If realloc cannot find enough space, it returns a null pointer, and leaves the previous region allocated.

Found by https://github.com/bryongloden/cppcheck

### CODE REVIEW

**Comment by KyroChi** [comment]
This repo is only a [mirror](https://fuchsia-review.googlesource.com/#/q/project:magenta).

**Comment by bryongloden** [comment]
@KyroChi and co, how do I get permission to push to magenta?

```
$ git clone https://fuchsia.googlesource.com/magenta
$ cd magenta/
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   system/uapp/launch/launch.c

no changes added to commit (use "git add" and/or "git commit -a")
$ git add system/uapp/launch/launch.c 
$ git commit -m 'properly handle common realloc() mistakes'
[master b37c3ec] properly handle common realloc() mistakes
 1 file changed, 27 insertions(+), 8 deletions(-)
$ git push
Counting objects: 10, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (10/10), done.
Writing objects: 100% (10/10), 1.45 KiB | 0 bytes/s, done.
Total 10 (delta 7), reused 0 (delta 0)
remote: Resolving deltas: 100% (7/7)
remote: Processing changes: refs: 1, done    
To https://fuchsia.googlesource.com/magenta
 ! [remote rejected] master -> master (prohibited by Gerrit)
error: failed to push some refs to 'https://fuchsia.googlesource.com/magenta'
$ 
```

**Comment by KyroChi** [comment]
[Read this](https://github.com/fuchsia-mirror/magenta/blob/master/docs/contributing.md) I don't actually have any association with Google or Fuchsia. I am guessing that they have a way to submit a PR on their main repo. Check that .md and look for stuff on their website. Sorry I don't have more for you.

**Comment by ocdtrekkie** [comment]
As a note, Googlers in IRC repetitively cited that the project was currently only open to submissions by Googlers, so I am not sure they are currently accepting. Though one would hope they might look at pulls here and consider grabbing them manually. Though if it's a legal or licensing question, they might be specifically avoiding doing so.

**Comment by SferaDev** [comment]
@bryongloden This github is just a mirror, hence it won't be reviewed in here. To sumbit for review you can either use jiri or git push to gerrit. First create an account on gerrit then git push ssh://fuchsia-review.googlesource.com:29418/magenta HEAD:refs/for/master.

@KyroChi The whole contribution readme is being rewritten on gerrit.

@ocdtrekkie Gerrit provides a CLA (Contributor License Agreement) that will be used to fix that legal problems. So whatever code pushed to gerrit doesn't belong to the commiter but to Google itself and the Fuchsia project. This happens on multiple OSS projects and it a common practice. Anyway, as you said, contributions are from Googlers (feature-wise) yet they encourage outsiders to provide bugfixes.

**Comment by bryongloden** [comment]
Well, now it's in https://fuchsia-review.googlesource.com/#/c/6940/.

@KyroChi 👍
@ocdtrekkie, can you recommend a IRC client for mac os x? I'm a noob at that 👍
@SferaDev, thank you. I had to authenticate to gerrit using HTTP/HTTPS because I couldn't find a way to [paste](https://gerrit-review.googlesource.com/Documentation/user-upload.html#configure_ssh) the content of my SSH public key file into gerrit’s web interface 👎

The final flow looked like this:

```
$ git clone https://fuchsia.googlesource.com/magenta
$ cd magenta/
$ git config --global user.email "cissp@bryongloden.com"
$ echo obtain a HTTP/HTTPS authentication password
$ echo add small bug fixes
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

    modified:   system/uapp/launch/launch.c

no changes added to commit (use "git add" and/or "git commit -a")
$ git add system/uapp/launch/launch.c 
$ git commit -m 'properly handle common realloc() mistakes'
$ curl -Lo `git rev-parse --git-dir`/hooks/commit-msg https://gerrit-review.googlesource.com/tools/hooks/commit-msg ; chmod +x `git rev-parse --git-dir`/hooks/commit-msg
$ git commit --amend
$ git push origin HEAD:refs/for/master
```

**Comment by SferaDev** [comment]
@bryongloden That's really weird it should be there but the menu doesn't show up here either. Either it's on purpose to force users to use jiri or a bad gerrit install. I use gerrit daily on other OSS projects and I'm quite used to the ssh endpoint (admins will be using it for everything starting from META to advanced push types). Anyway you should be able to access it from here: https://fuchsia-review.googlesource.com/#/settings/ssh-keys

Greetings!

**Pull request closed without merging**
